import { nanoid } from "nanoid"


const calculateDiscountedPrice = (price, discountRate) => {
    const rate = discountRate ?? 0;
    return price * (1 - rate / 100);
};


export const products = [
    {
        id: 1,
        title: "kadın yuvarlak yaka sweatshirt",
        name: "kapşonlu sweatshirt",
        imgList: ["/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_1.jpg",
            "/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_2.jpg",
            "/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_3.jpg",
            "/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_4.jpg"],
        gender: "kadın",
        gender_url: "kadın",
        category: "üst giyim",
        category_url: "ust-giyim",
        subcategory: "sweatshirt",
        subcategory_url: "sweatshirt",
        sizeList: ["s", "m", "l"],
        color: "siyah",
        colorHash: "black",
        price: 500,
        isDiscount: true,
        discountRate: 40,
        discountedPrice: calculateDiscountedPrice(500, 40),
    },
    {
        id: 2,
        title: "kadın kazak",
        name: "kazak",
        imgList: ["/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_1.jpg",
            "/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_2.jpg",
            "/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_3.jpg",
            "/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_4.jpg"],
        gender: "kadın",
        gender_url: "kadın",
        category: "üst giyim",
        category_url: "ust-giyim",
        subcategory: "kazak",
        subcategory_url: "kazak",
        sizeList: ["s", "m", "l"],
        color: "siyah",
        colorHash: "black",
        price: 500,
        isDiscount: true,
        discountRate: 40,
        discountedPrice: calculateDiscountedPrice(500, 40),
    },
    {
        id: 3,
        title: "kadın etek",
        name: "etek",
        imgList: ["/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_1.jpg",
            "/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_2.jpg",
            "/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_3.jpg",
            "/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_4.jpg"],
        gender: "kadın",
        gender_url: "kadın",
        category: "alt giyim",
        category_url: "alt-giyim",
        subcategory: "etek",
        subcategory_url: "etek",
        sizeList: ["s", "m", "l"],
        color: "siyah",
        colorHash: "black",
        price: 500,
        isDiscount: true,
        discountRate: 40,
        discountedPrice: calculateDiscountedPrice(500, 40),
    },
    {
        id: 3,
        title: "erkek şort",
        name: "şort",
        imgList: ["/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_1.jpg",
            "/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_2.jpg",
            "/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_3.jpg",
            "/Black_Hoodie_Woman/Beige_Sweatshirt_Woman_4.jpg"],
        gender: "erkek",
        gender_url: "erkek",
        category: "alt giyim",
        category_url: "alt-giyim",
        subcategory: "şort",
        subcategory_url: "sort",
        sizeList: ["s", "m", "l"],
        color: "siyah",
        colorHash: "black",
        price: 500,
        isDiscount: true,
        discountRate: 40,
        discountedPrice: calculateDiscountedPrice(500, 40),
    },

]